var OSName="Unknown OS";
if (navigator.appVersion.indexOf("Win")!=-1) OSName="ALT-F4";
else if (navigator.appVersion.indexOf("Mac")!=-1) OSName="COMMAND-Q";
else if (navigator.appVersion.indexOf("Linux")!=-1) OSName="ALT-F4";

function random_content(){
	var tip=new Array()
	
	tip[0]="Hello gamrs"
	tip[1]="Unfunny meme"
	tip[2]="Do you want to be my best friend\?"
	tip[3]="The only site made by Xenthio\."
	tip[4]="&lt;center&gt;&lt;h1&gt;Now in HTML\!&lt;/h1&gt;&lt;/center&gt;"
	tip[5]="How\'s it going m8\? ( &#865;&deg; &#860;&#662; &#865;&deg;)"
	tip[6]="Press "+OSName+"!"
	tip[7]="Bad command or file name."
	tip[8]="Bruh moment."
	tip[9]="Feeding Birds..."
	tip[10]="Delaying Episode 3..."
	tip[11]="Copying GMOD Loading Screen Splashes..."
	tip[12]="Begone newbie!"
	tip[13]="tip[13]=&quot;This is a Splash\!&quot;"
	tip[14]="You smell\!"
	tip[15]="PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP PLOP"
	tip[16]="This is a Splash\!"
	tip[17]="Splash Entry 17 cannot be found."
	tip[18]="For twen tee."
	tip[19]="As Seen on TV\!"
	tip[20]="Ecks Dee!"
	tip[21]="index.html\!"
	tip[22]="Gimme dat code.a"
	tip[23]="I made this splash in the car\!"
	tip[24]="chicken nuggets"
	tip[25]="Epic\!"
	tip[26]="Now With Free Robux\!"
	tip[27]="I am just some text."
	tip[28]="Next movie coming soon!"
	tip[29]="ecks dee\!"
	tip[30]="this is the 30th splash."
	tip[31]="X E N T H I O"
	tip[32]="all your base are belong to us"
	tip[33]="I'm running out of ideas for splashes.."
	tip[34]="&#x76;&#x61;&#x72;&#x20;&#x72;&#x74;&#x3D;&#x4D;&#x61;&#x74;&#x68;&#x2E;&#x66;&#x6C;&#x6F;&#x6F;&#x72;&#x28;&#x4D;&#x61;&#x74;&#x68;&#x2E;&#x72;&#x61;&#x6E;&#x64;&#x6F;&#x6D;&#x28;&#x29;&#x2A;&#x74;&#x69;&#x70;&#x2E;&#x6C;&#x65;&#x6E;&#x67;&#x74;&#x68;&#x29;"
	tip[35]="no u"
	tip[36]="where we droppin bois?"
	tip[37]="yo fam"
	tip[38]="This splash used to be something else, but then I realised I had no clue what it meant, so I changed it."
	tip[39]="error loading splash line 39, please report this bug to the developer"
	tip[40]="Ya mum"
	tip[41]="i should be doing something else, but instead im writing this!"
	tip[43]="That how to download graphics card meme no longer works because you can actually download a graphics card. It's called Nvidia GeForce Now"
	tip[44]=" "
	tip[45]="<IMG src=\"assets/7e6.gif\">"
	tip[46]="yeet"
	tip[47]="dxsPUhabABEF5gzPq51s6YFGrJAMHNVnr6d16dB/EimRXkvEH0BcOzeNZBK19vhF33kMGxdz3+eGorg1yw+TGpmxFlKT0YrWZ4GT9SPg1yr9Dm/BQGKYv3JOkD6FaqIrb1c5syfHKK3hpxOQaF0egm1l1hXmS41tEU0CLAb/znw2LydW89OnZQ==" // tip[47] + CB[?] + bl[?]wfis[?].js + base64 + encrypt code = ???? -->
	tip[48]="<strike>Half-Life 3</strike> Half-Life 1.5 1000$ VR only Edition"
	tip[49]="This site was made on a potato Laptop!"
	tip[50]="My friend is fat."
	tip[51]="Nothing to be seen here."
	tip[52]="Thank you based StuboUK."
	tip[53]="Rush B."
	tip[54]="Rush A."
	tip[55]="PogChamp"
	tip[56]="Boggers"
	tip[57]="Mug Moment"
	tip[58]="LETS GO FELLOW GAMERS"
	tip[59]="twitch.tv/jebook"
	tip[60]="subscibe to jebook"
	tip[61]="Do you want to buy solar panel?"
	tip[62]="WELCOME TO GBJ"
	tip[63]="subscribe to poopy stinky bum"
	tip[64]="Super Mario 64"
	tip[65]="Bruh moment"
	tip[66]="Bro how do I take the L?"
	tip[67]="ha"
	tip[68]="I built a website using only wish.com"
	tip[69]="this is tip 69, :)"
	tip[70]="ahhh b-"
	tip[71]=":wierD:"
	tip[72]="<IMG src=\"stuff/wierD.png\">"
	tip[73]="You've been bot rolled."
	tip[74]="Nice shot mate"
	tip[75]="uuhhhhhhhhhhhhhhhh, lemme think."
	tip[76]="Brush your teeth, bitch!"
	tip[77]="pizza is the bread"
	tip[78]="Where'd your mod go?"
	tip[79]="fucker"
	tip[80]="I wrote this."
	tip[81]="Xentho#9999"
	tip[82]="discord.gg/"
	tip[83]="This meme scuks"
	tip[84]="one too many open brackets"
	tip[85]="#splash.text"
	tip[86]="DO NOT delete the coconut."
	tip[87]="(Batteries not included.)"
	tip[88]="a"
	tip[89]="b"
	tip[90]="c"
	tip[91]="d"
	tip[92]="e"
	tip[93]="f"
	tip[94]="g"
	tip[95]="h"
	tip[96]="i"
	tip[97]="j"
	tip[98]="k"
	tip[99]="We just hit 100 splashes!"
	tip[100]="Sometimes good at programming!"
	tip[101]="Somewhat trustworthy!"
	tip[102]="Now a little more competent!"
	tip[103]="Only wastes a little bit of time!"

	var rt=Math.floor(Math.random()*tip.length)
	
	document.write(tip[rt])
}
random_content()
